version: '3.7'
services:
  node-app:
    build: node_app
    image: node-app:1.0
    ports:
      - '9999:9999'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'